version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/simple"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/equinox"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/invoker"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/invoker/src/it/dummy"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
